name: SmashSumo
main: me.cirnoslab.smashsumo.SmashSumo
version: 1.1.0
author: SuperN64
softdepend: [ktlibs-kotlin-stdlib, KotKit, KtLoader]
commands:
  smashsumo:
    description: Main command
    usage: /<command> [arena|join|leave|start]
    permission: smashsumo.use
    aliases: ss